#this is the item id of the item you want players to be able to use to select areas
SelectionItemId: 271

#this is a lag prevention setting, setting it to higher will mean less cpu usage but less precise player movement tracking.
#less precice movement tracking, means that a player may be able to spend a little time in a area he shouldn't
#have access to before he gets booted out.  this setting is in milliseconds.  default is 500 (half a second) which
#is a good balance between lag and safety.
MinMoveCheckInterval: 500

#how often protected areas are autosaved, in minutes
AutoSaveInterval: 10

#this is ONLY for if your either not using permissions, or you are using permissions and 
#a player is in a group that does not exist in the below groups configuration. in either case,
#residence will treat that player like he or she is in this group.
DefaultGroup: default

#globally enable or disable the land lease system.  this system requires users to renew or
#refresh their protections every X amount of days.  see the lease settings section under
#each group for controling this system
UseLeaseSystem: true

#how often to check for expired leases in minutes
LeaseCheckInterval: 10

#permissions control
EnablePermissions: true

#iConomy control
EnableIConomy: true

#enable buying and selling of residences, IConomy must be enabled for this to work
EnableBuySell: true

#if you just want to use this like a regular protection plugin, and not allow players to
#create residences and stuff, but make it OP/residence.admin only set this to true.
AdminsOnly: false

#these flags are applied whenever a player is outside a residence
WorldFlags:
    use: true
    build: false
    ignite: true
    firespread: true
    damage: true
    creeper: true
    tnt: true
    pvp: true

#these groups are the same as your permissions groups.  if you are not using permissions, everyone is in the "default" group.
Groups:
    default:
         CanCreate: true
         MaxX: 16
         MaxY: 256
         MaxZ: 16
         MoneyCost: 0.05
         MaxRes: 3
         AllowTeleport: true
         SubzoneDepth: 3
         CanSetMessages: true
         DefaultEnterMessage: Welcome %player to %residence, owned by %owner.
         DefaultLeaveMessage: Now leaving %residence.
         MaxResidenceAreas: 2
         Lease:
              MaxDays: 16
              RenewTime: 14
              RenewCost: 0.02
         Economy:
              CanBuy: true
              CanSell: false
              BuyIgnoreLimits: false
         FlagPermissions:
              move: true
              build: true
              use: true
         ResidenceDefaultFlags:
              build: false
              use: false
         CreatorDefaultFlags:
              move: true
              build: true
              use: true
         GroupDefaultFlags:
              #default:
                   #build: true
PlayerGroupAssigments:
     bekvon: default